// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'md': string;
  'preview': string;
  'publish': string;
}
export const cssExports: CssExports;
export default cssExports;
