// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'abstract': string;
  'content': string;
  'line': string;
  'listItem': string;
  'text': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
