// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'loadingCenterAbsolute': string;
  'object': string;
  'object0': string;
  'object1': string;
  'object2': string;
  'object3': string;
  'object4': string;
  'pageLoading': string;
}
export const cssExports: CssExports;
export default cssExports;
